package com.backset.forze.module.budgeting.security;

public enum ForzePermission {
	PROYECTOS_READ,
	PROYECTOS_WRITE,
	PRESUPUESTOS_READ,
	PRESUPUESTOS_WRITE,
	CATALOGOS_READ,
	CATALOGOS_WRITE,
	PROVEEDORES_READ,
	PROVEEDORES_WRITE,
	APROBACIONES_READ,
	APROBACIONES_WRITE,
	DOCUMENTOS_READ,
	DOCUMENTOS_WRITE,
	ADMINISTRACION_READ,
	ADMINISTRACION_WRITE,
	AUDITORIA_READ
}
