spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.thymeleaf.cache=false

forze.security.cookie-secure=false
forze.security.cookie-same-site=Lax
forze.bootstrap.admin.enabled=${ADMIN_BOOTSTRAP_ENABLED:true}
