spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

forze.security.cookie-secure=true
forze.security.cookie-same-site=Strict
forze.bootstrap.admin.enabled=false
