spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.url=${FLYWAY_URL:${DB_URL}}
spring.flyway.user=${FLYWAY_USER:${DB_USERNAME}}
spring.flyway.password=${FLYWAY_PASSWORD:${DB_PASSWORD}}
spring.thymeleaf.cache=false

management.tracing.enabled=false
springdoc.api-docs.enabled=true

forze.security.cookie-secure=false
forze.security.cookie-same-site=Lax
forze.bootstrap.admin.enabled=false
